export enum IDropdownOptionEnum {
    id = 'id',
    key = 'key',
    value = 'value',
}

export enum IOrganisationStatusEnum {
    government = 'Government',
    nonProfit = 'Not for Profit',
    profit = 'Profit',
    private = 'Private',
    other = 'Other',
}
export enum IMainAudienceEnum {
    employers = 'Employers',
    bothEmployeeAndEmployer = 'Both Employee and Employer',
    other = 'Other',
}
export enum ITrainingEnum {
    f2f = 'F2F',
    virtualAndOnline = 'virtual and online',
}
export enum IYesNoEnum {
    yes = 'Yes',
    no = 'No',
    notAvailable = 'n/a',
}
export enum IPolicyAndAdvocacyActivityNameEnum {
    submissions = 'Submissions',
    whitePapers = 'White Papers',
    reports = 'Reports',
    other = 'Other',
    positionStatements = 'Position Statements',
    informationPapers = 'Information Papers',
    researchReports = 'Research Reports',
    strategicAlliances = 'Strategic Alliances Within',
}
export enum IResourceActivityEnum {
    mentalHealthConditions = 'Mental health conditions',
    psychologicalHazards = 'Psychosocial hazards ',
    regulation = 'Regulation',
    workplaceStrategiesAndTools = 'Workplace strategies & tools',
    supportingRecovery = 'Supporting recovery',
    training = 'Training',
    managerTraining = 'Manager Training',
    allWorkersTraining = 'All Workers Training',
    other = 'Other',
}
export enum IResourceTopicEnum {
    lawAndRegulation = 'Law and regulation',
    workersCompensation = `Worker's compensation`,
    statisticsAndResearch = 'Statistics and research',
    workplaceMentalHealthSafety = 'Workplace Mental Health safety',
    workplaceMentalHealthPracticeGuides = 'Workplace Mental Health practice guides',
    covidInformationForWorkplaces = 'COVID information for workplaces',
    personalResourcesAndSupport = 'Personal resources and support',
    digitalToolsAndApps = 'Digital tools & apps',
    workplaceWellbeing = 'Workplace wellbeing',
    healthProfessionalAndCommunityAndSchoolResources = 'Health Professional Resources, Community and School Resources',
    onlineProgramsMindarma = 'Online Programs - Mindarma',
    webinars = 'Webinars',
    programsWorkshops = 'Programs - workshops',
    programsPresentations = 'Programs - presentations',
    workplaceToolkit = 'Workplace toolkit',
    headsUp = 'Heads up',
    reviewOfTheResearch = 'Review of the research',
    yourMentalHealthTelatedToWorkplace = 'Your mental health (as it relates to the workplace)',
    healthyWorkplacesGeneralGuidance = 'Healthy Workplaces - general guidance',
    supportingOthersRelatedToWorkplace = 'Supporting others (as it relates to the workplace)',
    healthyWorkplacesComprehensiveResources = 'Healthy Workplaces - comprehensive resources',
    healthyWorkplacesBusinessActionPlan = 'Healthy Workplaces - business action plan',
    indicatorsOfAThrivingWorkplaceReport = 'Indicators of a Thriving Workplace Report ',
    workplaceConsultingServices = 'Workplace consulting services',
    personalResources = 'Personal resources',
    additionalSituationSpecificResources = 'Additional situation specific resources ',
    saneGuideToMHInTheWorkplace = 'SANE guide to MH in the workplace',
    personalResourcesToSupportThoseWithMH = 'Personal resources to support those in the workplace with MH',
    generalResources = 'General resources ',
    recoveryAtWorkToolkit = 'Recovery at Work toolkit',
    managerToolsAndResurces = 'Manager tools & resources ',
    smallBusinessToolsAndResources = 'Small business tools & resources',
    overarchingNSWMHWorkplaces = 'Overarching NSW Mentally Healthy Workplaces (Strategy to 2022)',
    mhCapabilityCheck = 'Mental Health Capability Check',
    mentalHealthCheckup = 'Mental Health Check Up',
    businessStressorScreen = 'Business stressor screen',
    welbeingPlan = 'Wellbeing Plan',
    generalInformation = 'General information',
    flexibleWorkResources = 'Flexible work resources',
    workingFromHomeResources = 'Working from home resources',
    workDesignResources = 'Work Design resources',
    thriveAtWork = 'Thrive at Work',
    smallHubBusiness = 'Small business hub',
    workplaceWellbeingAndCovidSupport = 'Workplace wellbeing & COVID-19 support',
    memberOnlyResourceLibrary = 'Member only resource library',
    naturalDisasterSupport = 'Natural Disaster Support',
    blogsAndNews = 'Blogs and news ',
    information = 'Information',
    workplaceGuidanceOnAskingRUOK = 'Workplace guide on asking RUOK',
    workplacePresentation = 'Workplace presentation',
    generalOverview = 'General overview',
    workWellToolkit = 'Workwell toolkit',
    mentalHealthInjury = 'Mental Health Injury support for employees',
    guideForPreventingAndManagingWorkRelatedStress = 'Guide for preventing and managing work related stress - for employers',
    deepDiveOnTopics = 'Deep dives on the following topics - occupational violence and aggression; bullying; fatigue; work related gendered violence; work related stress',
    peopleAtWorkProcesses = 'People at Work processes',
    resourcesForWorkplaces = 'Resources for Workplaces',
    resourcesForWorkers = 'Resources for Workers',
    comcareLMS = 'Comcare LMS',
    benefitsOfSafeAndHealthyWorkplace = 'Benefits of Safe and Healthy Workplace',
    interveneEarlyAndKnowTheWarningSigns = 'Intervene early and know the warning signs',
    workHealthAndSafetyManagementSystem = 'Work, Health and Safety Management System',
    goodWorkDesign = 'Good Work Design',
    investingInExperience = 'Investing in experience',
    mentallyHealthWorkplacesToolkit = 'Mentally Health Workplaces Toolkit',
    psychologicalHazardsAndFactors = 'Psychosocial hazards and factors',
    mentalHealthWebinars = 'Mental Health webinars',
    organisationalStrategies = 'Organisational Strategies ',
    guardingMindsAtWork = 'Guarding Minds at Work',
    approqachesForPeopleAndLeadersEmployeeConcerns = 'Approaches for People Leaders - Employee Concerns',
    approqachesForPeopleAndLeadersLeadershipSkills = 'Approaches for People Leaders - Leadership Skills',
    approqachesForPeopleAndLeadersTeamWorkshops = 'Approaches for People Leaders - Team Workshops',
    lawAndLegislationResourcesForEmployees = 'Resources for Employees',
    lawAndLegislationAssessmentsToolsAndWorkshops = 'Assessments, Tools and Workshops',
    takingCareOf = 'Taking care of yourself at work',
    takingCareOfYourStaff = 'Taking care of your staff',
    takingCareOfYourStaffThrivingAtWork = 'Taking care of your staff - Thriving at Work',
    takingCareOfYourStaffWorkplaceWellbeingIndex = 'Taking Care of your Staff - Workplace Wellbeing Index',
    takingCareOfYourStaffInfluenceAndParticipationToolkit = 'Taking Care of Your Staff - Influence and Participation Toolkit',
    bellSealCertification = 'Bell Seal Certification',
    resourcesForEmployers = 'Resources for Employers',
    workplaceResearch = 'Workplace Research',
    howToSupportMentalHealthAtWorkGuide = 'How to support mental health at work - guide',
    mentalHealthAtWork = 'Mental Health at Work',
    blogs = 'Blogs',
    discriminationAtWork = 'Discrimination at work',
    seeMeInWorkProgramme = 'See Me in Work Programme',
    LetsChatToolkit = `Let's Chat toolkit`,
    eLearningPlatform = 'Elearning platform',
    importanceOfGoodMentalHealthAtWorkForEmployers = 'Importance of good mental health at work (for employers)',
    supportingMentalHealthForEmployers = 'Supporting mental health (for employers)',
    stressAtWork = 'Stress at work',
    nationalStandardOfCanada = 'National Standard of Canada for Psychological Health and Safety in the Workplace.',
    posters = 'Posters',
    mindsMatterAssessmentTool = 'MindsMatter assessment tool',
    collectionOfReportsByMHCC = 'Collection of reports by MHCC',
    psychologicalHealthAndSafetyAnActionGuideForEmployers = 'Psychological Health and Safety: An Action Guide for Employers',
    webinarSeries = 'Webinar series',
    generalOverviewOfWorkRelatedStress = 'General overview of work related stress',
    stressRiskAssessment = 'Stress risk assessment',
    hseManagementStandards = `HSE's Management Standards`,
    tacklingWorkRelatedStressUsingStandardsApproach = `Tackling work-related stress using the Management Standards approach
  A step-by-step workbook`,
    returnToWorkQuestionnaire = 'Return to work questionnaire relating to 6 work design factors',
    lineManagersResource = `Line Managers’ Resource
  A practical guide to managing and supporting people with mental health problems in the workplace`,
    lineManagerCompetencyIndicator = 'Line Manager Competency Indicator Tool',
    stressTalkingToolkit = 'Stress - Talking Toolkit',
    workplaceWellnessAndYouManagingAndThrivingInCOVIDTimes = 'Workplace Wellness and You: Managing and Thriving in the time of COVID-19',
    recommendedArticles = 'Recommended articles',
    ceoTreesOfAspirationAndAction = `CEO's trees of aspiration and action`,
}
